M48
; DRILL file {KiCad 8.0.2} date 2024-10-21T17:53:25+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-21T17:53:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.439Y-1.9673
X1.439Y-2.1949
T2
X7.1606Y-2.8957
X7.1634Y-2.3485
X7.3969Y-2.8957
X7.3996Y-2.3485
M30
